default: TicTacToeWinCheck

main.o: main.c 
	gcc -std=c99 -c main.c -o main.o

TicTacToeWinCheck: main.o
	gcc -std=c99 main.o -o TicTacToeWinCheck


#CC = gcc
#CFLAGS = -std=c99

#main: main.c
#     $(CC) -o TicTacToeWinCheck main.c

#gcc -std=c99 main.c -o TicTacToeWinCheck